#include "control_sequences.h"
#include "KeyCodes.h"

// using ShortcutAction = Hexe::Terminal::ShortcutAction;

struct key_t
{
    keycode   keysym;
    modifiers mask;
    string_t  string;
    int       appkey;
    int       appcursor;
};

// static Shortcut shortcuts[] = { { keycode::INSERT, modifiers::SHIFT, ShortcutAction::PASTE, 0, 0 } };
// clang-format off
static key_t keys[] = {
    /* keysym               mask                string       appkey appcursor */
    // { KeyCodes::KEYPAD_ENTER,      ANY,            "\x1BOM",    +2,  0 },
    { keycode::KEYPAD_ENTER,      modifiers::ANY,            "\r",        -1,  0 },
    { keycode::UP,                modifiers::SHIFT,          "\x1B[1;2A",  0,  0 },
    { keycode::UP,                modifiers::ALT,            "\x1B[1;3A",  0,  0 },
    { keycode::UP,                modifiers::ALT_SHIFT,      "\x1B[1;4A",  0,  0 },
    { keycode::UP,                modifiers::CTRL,           "\x1B[1;5A",  0,  0 },
    { keycode::UP,                modifiers::CTRL_SHIFT,     "\x1B[1;6A",  0,  0 },
    { keycode::UP,                modifiers::CTRL_ALT,       "\x1B[1;7A",  0,  0 },
    { keycode::UP,                modifiers::CTRL_ALT_SHIFT, "\x1B[1;8A",  0,  0 },
    { keycode::UP,                modifiers::ANY,            "\x1B[A",     0, -1 },
    // { KeyCodes::UP,             modifiers::   ANY,            "\x1BOA",     0, +1 },
    { keycode::DOWN,              modifiers::SHIFT,          "\x1B[1;2B",  0,  0 },
    { keycode::DOWN,              modifiers::ALT,            "\x1B[1;3B",  0,  0 },
    { keycode::DOWN,              modifiers::ALT_SHIFT,      "\x1B[1;4B",  0,  0 },
    { keycode::DOWN,              modifiers::CTRL,           "\x1B[1;5B",  0,  0 },
    { keycode::DOWN,              modifiers::CTRL_SHIFT,     "\x1B[1;6B",  0,  0 },
    { keycode::DOWN,              modifiers::CTRL_ALT,       "\x1B[1;7B",  0,  0 },
    { keycode::DOWN,              modifiers::CTRL_ALT_SHIFT, "\x1B[1;8B",  0,  0 },
    { keycode::DOWN,              modifiers::ANY,            "\x1B[B",     0, -1 },
    // { KeyCodes::DOWN,           modifiers::   ANY,            "\x1BOB",     0, +1 },
    { keycode::LEFT,              modifiers::SHIFT,          "\x1B[1;2D",  0,  0 },
    { keycode::LEFT,              modifiers::ALT,            "\x1B[1;3D",  0,  0 },
    { keycode::LEFT,              modifiers::ALT_SHIFT,      "\x1B[1;4D",  0,  0 },
    { keycode::LEFT,              modifiers::CTRL,           "\x1B[1;5D",  0,  0 },
    { keycode::LEFT,              modifiers::CTRL_SHIFT,     "\x1B[1;6D",  0,  0 },
    { keycode::LEFT,              modifiers::CTRL_ALT,       "\x1B[1;7D",  0,  0 },
    { keycode::LEFT,              modifiers::CTRL_ALT_SHIFT, "\x1B[1;8D",  0,  0 },
    { keycode::LEFT,              modifiers::ANY,            "\x1B[D",     0, -1 },
    // { KeyCodes::LEFT,           modifiers::   ANY,            "\x1BOD",     0, +1 },
    { keycode::RIGHT,             modifiers::SHIFT,          "\x1B[1;2C",  0,  0 },
    { keycode::RIGHT,             modifiers::ALT,            "\x1B[1;3C",  0,  0 },
    { keycode::RIGHT,             modifiers::ALT_SHIFT,      "\x1B[1;4C",  0,  0 },
    { keycode::RIGHT,             modifiers::CTRL,           "\x1B[1;5C",  0,  0 },
    { keycode::RIGHT,             modifiers::CTRL_SHIFT,     "\x1B[1;6C",  0,  0 },
    { keycode::RIGHT,             modifiers::CTRL_ALT,       "\x1B[1;7C",  0,  0 },
    { keycode::RIGHT,             modifiers::CTRL_ALT_SHIFT, "\x1B[1;8C",  0,  0 },
    { keycode::RIGHT,             modifiers::ANY,            "\x1B[C",     0, -1 },
    // { KeyCodes::RIGHT,          modifiers::   ANY,            "\x1BOC",     0, +1 },
    { keycode::TAB,               modifiers::SHIFT,          "\x1B[Z",     0,  0 },
    { keycode::TAB,               modifiers::ANY,            "\t",         0,  0 },
    { keycode::ENTER,             modifiers::ALT,            "\x1B\r",     0,  0 },
    { keycode::ENTER,             modifiers::ANY,            "\r",         0,  0 },
    { keycode::INSERT,            modifiers::SHIFT,          "\x1B[4l",   -1,  0 },
    // { KeyCodes::INSERT,         modifiers::   SHIFT,          "\x1B[2;2~", +1,  0 },
    { keycode::INSERT,            modifiers::CTRL,           "\x1B[L",    -1,  0 },
    // { KeyCodes::INSERT,         modifiers::   CTRL,           "\x1B[2;5~", +1,  0 },
    { keycode::INSERT,            modifiers::ANY,            "\x1B[4h",   -1,  0 },
    // { KeyCodes::INSERT,         modifiers::   ANY,            "\x1B[2~",   +1,  0 },
    { keycode::DELETE_K,            modifiers::CTRL,           "\x1B[M",    -1,  0 },
    // { KeyCodes::DELETE_K,         modifiers::   CTRL,           "\x1B[3;5~", +1,  0 },
    { keycode::DELETE_K,            modifiers::SHIFT,          "\x1B[2K",   -1,  0 },
    // { KeyCodes::DELETE_K,         modifiers::   SHIFT,          "\x1B[3;2~", +1,  0 },
    { keycode::DELETE_K,            modifiers::ANY,            "\x1B[P",    -1,  0 },
    // { KeyCodes::DELETE_K,         modifiers::   ANY,            "\x1B[3~",   +1,  0 },
    { keycode::BACKSPACE,         modifiers::NONE,           "\177",       0,  0 },
    { keycode::BACKSPACE,         modifiers::ALT,            "\x1B\177",   0,  0 },
    { keycode::HOME,              modifiers::SHIFT,          "\x1B[2J",    0, -1 },
    // { KeyCodes::HOME,           modifiers::   SHIFT,          "\x1B[1;2H",  0, +1 },
    { keycode::HOME,              modifiers::ANY,            "\x1B[H",     0, -1 },
    // { KeyCodes::HOME,           modifiers::   ANY,            "\x1B[1~",    0, +1 },
    { keycode::END,               modifiers::CTRL,           "\x1B[J",    -1,  0 },
    // { KeyCodes::END,            modifiers::   CTRL,           "\x1B[1;5F", +1,  0 },
    { keycode::END,               modifiers::SHIFT,          "\x1B[K",    -1,  0 },
    // { KeyCodes::END,            modifiers::   SHIFT,          "\x1B[1;2F", +1,  0 },
    { keycode::END,               modifiers::ANY,            "\x1B[4~",    0,  0 },
    { keycode::ESCAPE,            modifiers::ANY,            "\x1B",       0,  0 },
    { keycode::PAGE_UP,           modifiers::NONE,           "\x1B[5~",    0,  0 },
    { keycode::PAGE_DOWN,         modifiers::NONE,           "\x1B[6~",    0,  0 },
    { keycode::PAGE_UP,           modifiers::CTRL,           "\x1B[5;5~",  0, 0 },
    { keycode::PAGE_UP,           modifiers::CTRL,           "\x1B[5;5~",  0, 0 },
    { keycode::PAGE_UP,           modifiers::SHIFT,          "\x1B[5;2~",  0, 0 },
    { keycode::PAGE_UP,           modifiers::ANY,            "\x1B[5~",    0, 0 },
    { keycode::BACKSPACE,         modifiers::CTRL,           "\x1B[M",    -1, 0 },
    // { KeyCodes::BACKSPACE,      modifiers::   CTRL,           "\x1B[3;5~", +1, 0 },
    { keycode::BACKSPACE,         modifiers::SHIFT,          "\x1B[2K",   -1, 0 },
    // { KeyCodes::BACKSPACE,      modifiers::   SHIFT,          "\x1B[3;2~", +1, 0 },
    { keycode::BACKSPACE,         modifiers::ANY,            "\x1B[P",    -1, 0 },
    // { KeyCodes::BACKSPACE,      modifiers::   ANY,            "\x1B[3~",   +1, 0 },
    // { KeyCodes::KEYPAD_SUBTRACT,modifiers::   ANY,            "\x1BOm",    +2, 0 },
    // { KeyCodes::KEYPAD_DECIMAL, modifiers::   ANY,            "\x1BOn",    +2, 0 },
    // { KeyCodes::KEYPAD_DIVIDE,  modifiers::   ANY,            "\x1BOo",    +2, 0 },
    // { KeyCodes::KEYPAD_MULTIPLY,modifiers::   ANY,            "\x1BOj",    +2, 0 },
    // { KeyCodes::KEYPAD_ADD,     modifiers::   ANY,            "\x1BOk",    +2, 0 },
    { keycode::F1,                modifiers::NONE,           "\x1BOP",     0, 0 },
    { keycode::F1, /* F13 */      modifiers::SHIFT,          "\x1B[1;2P",  0, 0 },
    { keycode::F1, /* F25 */      modifiers::CTRL,           "\x1B[1;5P",  0, 0 },
    { keycode::F1, /* F37 */      modifiers::SUPER,          "\x1B[1;6P",  0, 0 },
    { keycode::F1, /* F49 */      modifiers::ALT,            "\x1B[1;3P",  0, 0 },
    { keycode::F1, /* F61 */      modifiers::CTRL_ALT,       "\x1B[1;4P",  0, 0 },
    { keycode::F2,                modifiers::NONE,           "\x1BOQ",     0, 0 },
    { keycode::F2, /* F14 */      modifiers::SHIFT,          "\x1B[1;2Q",  0, 0 },
    { keycode::F2, /* F26 */      modifiers::CTRL,           "\x1B[1;5Q",  0, 0 },
    { keycode::F2, /* F38 */      modifiers::SUPER,          "\x1B[1;6Q",  0, 0 },
    { keycode::F2, /* F50 */      modifiers::ALT,            "\x1B[1;3Q",  0, 0 },
    { keycode::F2, /* F62 */      modifiers::CTRL_ALT,       "\x1B[1;4Q",  0, 0 },
    { keycode::F3,                modifiers::NONE,           "\x1BOR",     0, 0 },
    { keycode::F3, /* F15 */      modifiers::SHIFT,          "\x1B[1;2R",  0, 0 },
    { keycode::F3, /* F27 */      modifiers::CTRL,           "\x1B[1;5R",  0, 0 },
    { keycode::F3, /* F39 */      modifiers::SUPER,          "\x1B[1;6R",  0, 0 },
    { keycode::F3, /* F51 */      modifiers::ALT,            "\x1B[1;3R",  0, 0 },
    { keycode::F3, /* F63 */      modifiers::CTRL_ALT,       "\x1B[1;4R",  0, 0 },
    { keycode::F4,                modifiers::NONE,           "\x1BOS",     0, 0 },
    { keycode::F4, /* F16 */      modifiers::SHIFT,          "\x1B[1;2S",  0, 0 },
    { keycode::F4, /* F28 */      modifiers::CTRL,           "\x1B[1;5S",  0, 0 },
    { keycode::F4, /* F40 */      modifiers::SUPER,          "\x1B[1;6S",  0, 0 },
    { keycode::F4, /* F52 */      modifiers::ALT,            "\x1B[1;3S",  0, 0 },
    { keycode::F5,                modifiers::NONE,           "\x1B[15~",   0, 0 },
    { keycode::F5, /* F17 */      modifiers::SHIFT,          "\x1B[15;2~", 0, 0 },
    { keycode::F5, /* F29 */      modifiers::CTRL,           "\x1B[15;5~", 0, 0 },
    { keycode::F5, /* F41 */      modifiers::SUPER,          "\x1B[15;6~", 0, 0 },
    { keycode::F5, /* F53 */      modifiers::ALT,            "\x1B[15;3~", 0, 0 },
    { keycode::F6,                modifiers::NONE,           "\x1B[17~",   0, 0 },
    { keycode::F6, /* F18 */      modifiers::SHIFT,          "\x1B[17;2~", 0, 0 },
    { keycode::F6, /* F30 */      modifiers::CTRL,           "\x1B[17;5~", 0, 0 },
    { keycode::F6, /* F42 */      modifiers::SUPER,          "\x1B[17;6~", 0, 0 },
    { keycode::F6, /* F54 */      modifiers::ALT,            "\x1B[17;3~", 0, 0 },
    { keycode::F7,                modifiers::NONE,           "\x1B[18~",   0, 0 },
    { keycode::F7, /* F19 */      modifiers::SHIFT,          "\x1B[18;2~", 0, 0 },
    { keycode::F7, /* F31 */      modifiers::CTRL,           "\x1B[18;5~", 0, 0 },
    { keycode::F7, /* F43 */      modifiers::SUPER,          "\x1B[18;6~", 0, 0 },
    { keycode::F7, /* F55 */      modifiers::ALT,            "\x1B[18;3~", 0, 0 },
    { keycode::F8,                modifiers::NONE,           "\x1B[19~",   0, 0 },
    { keycode::F8, /* F20 */      modifiers::SHIFT,          "\x1B[19;2~", 0, 0 },
    { keycode::F8, /* F32 */      modifiers::CTRL,           "\x1B[19;5~", 0, 0 },
    { keycode::F8, /* F44 */      modifiers::SUPER,          "\x1B[19;6~", 0, 0 },
    { keycode::F8, /* F56 */      modifiers::ALT,            "\x1B[19;3~", 0, 0 },
    { keycode::F9,                modifiers::NONE,           "\x1B[20~",   0, 0 },
    { keycode::F9, /* F21 */      modifiers::SHIFT,          "\x1B[20;2~", 0, 0 },
    { keycode::F9, /* F33 */      modifiers::CTRL,           "\x1B[20;5~", 0, 0 },
    { keycode::F9, /* F45 */      modifiers::SUPER,          "\x1B[20;6~", 0, 0 },
    { keycode::F9, /* F57 */      modifiers::ALT,            "\x1B[20;3~", 0, 0 },
    { keycode::F10,               modifiers::NONE,           "\x1B[21~",   0, 0 },
    { keycode::F10, /* F22 */     modifiers::SHIFT,          "\x1B[21;2~", 0, 0 },
    { keycode::F10, /* F34 */     modifiers::CTRL,           "\x1B[21;5~", 0, 0 },
    { keycode::F10, /* F46 */     modifiers::SUPER,          "\x1B[21;6~", 0, 0 },
    { keycode::F10, /* F58 */     modifiers::ALT,            "\x1B[21;3~", 0, 0 },
    { keycode::F11,               modifiers::NONE,           "\x1B[23~",   0, 0 },
    { keycode::F11, /* F23 */     modifiers::SHIFT,          "\x1B[23;2~", 0, 0 },
    { keycode::F11, /* F35 */     modifiers::CTRL,           "\x1B[23;5~", 0, 0 },
    { keycode::F11, /* F47 */     modifiers::SUPER,          "\x1B[23;6~", 0, 0 },
    { keycode::F11, /* F59 */     modifiers::ALT,            "\x1B[23;3~", 0, 0 },
    { keycode::F12,               modifiers::NONE,           "\x1B[24~",   0, 0 },
    { keycode::F12, /* F24 */     modifiers::SHIFT,          "\x1B[24;2~", 0, 0 },
    { keycode::F12, /* F36 */     modifiers::CTRL,           "\x1B[24;5~", 0, 0 },
    { keycode::F12, /* F48 */     modifiers::SUPER,          "\x1B[24;6~", 0, 0 },
    { keycode::F12, /* F60 */     modifiers::ALT,            "\x1B[24;3~", 0, 0 },
    { keycode::F13,               modifiers::NONE,           "\x1B[1;2P",  0, 0 },
    { keycode::F14,               modifiers::NONE,           "\x1B[1;2Q",  0, 0 },
    { keycode::F15,               modifiers::NONE,           "\x1B[1;2R",  0, 0 },
    { keycode::F16,               modifiers::NONE,           "\x1B[1;2S",  0, 0 },
    { keycode::F17,               modifiers::NONE,           "\x1B[15;2~", 0, 0 },
    { keycode::F18,               modifiers::NONE,           "\x1B[17;2~", 0, 0 },
    { keycode::F19,               modifiers::NONE,           "\x1B[18;2~", 0, 0 },
    { keycode::F20,               modifiers::NONE,           "\x1B[19;2~", 0, 0 },
    { keycode::F21,               modifiers::NONE,           "\x1B[20;2~", 0, 0 },
    { keycode::F22,               modifiers::NONE,           "\x1B[21;2~", 0, 0 },
    { keycode::F23,               modifiers::NONE,           "\x1B[23;2~", 0, 0 },
    { keycode::F24,               modifiers::NONE,           "\x1B[24;2~", 0, 0 }
    // { KeyCodes::KEYPAD_0,       modifiers::   ANY,            "\x1BOp",    +2, 0 },
    // { KeyCodes::KEYPAD_1,       modifiers::   ANY,            "\x1BOq",    +2, 0 },
    // { KeyCodes::KEYPAD_2,       modifiers::   ANY,            "\x1BOr",    +2, 0 },
    // { KeyCodes::KEYPAD_3,       modifiers::   ANY,            "\x1BOs",    +2, 0 },
    // { KeyCodes::KEYPAD_4,       modifiers::   ANY,            "\x1BOt",    +2, 0 },
    // { KeyCodes::KEYPAD_5,       modifiers::   ANY,            "\x1BOu",    +2, 0 },
    // { KeyCodes::KEYPAD_6,       modifiers::   ANY,            "\x1BOv",    +2, 0 },
    // { KeyCodes::KEYPAD_7,       modifiers::   ANY,            "\x1BOw",    +2, 0 },
    // { KeyCodes::KEYPAD_8,       modifiers::   ANY,            "\x1BOx",    +2, 0 },
    // { KeyCodes::KEYPAD_9,       modifiers::   ANY,            "\x1BOy",    +2, 0 }
};

ControlSequences::ControlSequences()
{
    size_t controlSequenceCount = sizeof( keys ) / sizeof( key_t );
    for( int i = 0; i < controlSequenceCount; i++ )
    {
        if( keys[i].mask == modifiers::ANY )
        {
            for( int j = 0; j < (size_t)modifiers::COUNT; j++ )
                controlSequences[(size_t)keys[i].keysym][j] = keys[i].string;
        }
        else
        {
            controlSequences[(size_t)keys[i].keysym][(size_t)keys[i].mask] = keys[i].string;
        }
    }
}
