import os
import sys
# os.system("")

print("\x1b[0mDISPLAY MODES")
print("\x1b[0m=====================================")
print("\x1b[0m[ NORMAL MODE        ] Hello World!!!")
print("\x1b[1m[ BOLD MODE          ] Hello World!!!\x1b[0m")
print("\x1b[2m[ FAINT MODE         ] Hello World!!!\x1b[0m")
print("\x1b[3m[ ITALIC MODE        ] Hello World!!!\x1b[0m")
print("\x1b[4m[ UNDERLINE MODE     ] Hello World!!!\x1b[0m")
print("\x1b[5m[ BLINKING MODE      ] Hello World!!!\x1b[0m")
print("\x1b[7m[ REVERSE MODE       ] Hello World!!!\x1b[0m")
print("\x1b[8m[ HIDDEN MODE        ] Hello World!!!\x1b[0m")
print("\x1b[9m[ STRIKETHROUGH MODE ] Hello World!!!\x1b[0m")

print()
print('Basic Foreground Colors:')
print('\t\x1b[30mBlack foreground\x1b[0m')
print('\t\x1b[31mRed foreground\x1b[0m')
print('\t\x1b[32mGreen foreground\x1b[0m')
print('\t\x1b[33mYellow foreground\x1b[0m')
print('\t\x1b[34mBlue foreground\x1b[0m')
print('\t\x1b[35mMagenta foreground\x1b[0m')
print('\t\x1b[36mCyan foreground\x1b[0m')
print('\t\x1b[37mWhite foreground\x1b[0m')
print('\t\x1b[39mDefault foreground color \x1b[0m')

print()
print('Basic Background Colors:')
print('\t\x1b[40mBlack background         \x1b[0m')
print('\t\x1b[41mRed background           \x1b[0m')
print('\t\x1b[42mGreen background         \x1b[0m')
print('\t\x1b[43mYellow background        \x1b[0m')
print('\t\x1b[44mBlue background          \x1b[0m')
print('\t\x1b[45mMagenta background       \x1b[0m')
print('\t\x1b[46mCyan background          \x1b[0m')
print('\t\x1b[47mWhite background         \x1b[0m')
print('\t\x1b[49mDefault background color \x1b[0m')

print()
print('Bright Foreground Colors:')
print('\t\x1b[90mBright Black foreground \x1b[0m')
print('\t\x1b[91mBright Red foreground\x1b[0m')
print('\t\x1b[92mBright Green foreground\x1b[0m')
print('\t\x1b[93mBright Yellow foreground\x1b[0m')
print('\t\x1b[94mBright Blue foreground\x1b[0m')
print('\t\x1b[95mBright Magenta foreground\x1b[0m')
print('\t\x1b[96mBright Cyan foreground\x1b[0m')
print('\t\x1b[97mBright White foreground\x1b[0m')

print()
print('Bright Background Colors:')
print('\t\x1b[100mBright Black background   \x1b[0m')
print('\t\x1b[101mBright Red background     \x1b[0m')
print('\t\x1b[102mBright Green background   \x1b[0m')
print('\t\x1b[103mBright Yellow background  \x1b[0m')
print('\t\x1b[104mBright Blue background    \x1b[0m')
print('\t\x1b[105mBright Magenta background \x1b[0m')
print('\t\x1b[106mBright Cyan background    \x1b[0m')
print('\t\x1b[107mBright White background   \x1b[0m')
print('\x1b[107m\x1b[30C\x1b[m')

# print('\t\x1b[101m                                                                                 \x1b[0m')
